LATEX_FILES = rapport.aux rapport.fdb_latexmk rapport.fls rapport.log rapport.pdf\
			  rapport.synctex.gz rapport.out
LATEX_DIR = svg-inkscape

clean:
	@rm -f $(SUBMISSION_ARCHIVE)

	@cd rapport; rm -f $(LATEX_FILES); rm -rf $(LATEX_DIR)